require 'default.rb'
require 'defaultMappingRegistry.rb'
require 'soap/rpc/driver'

class SugarsoapPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "http://crm.automatedlabs.com/soap.php"
  NsSugarcrm = "http://www.sugarcrm.com/sugarcrm"

  Methods = [
    [ XSD::QName.new(NsSugarcrm, "is_user_admin"),
      "http://crm.automatedlabs.com/soap.php/is_user_admin",
      "is_user_admin",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "login"),
      "http://crm.automatedlabs.com/soap.php/login",
      "login",
      [ ["in", "user_auth", ["User_auth", "http://www.sugarcrm.com/sugarcrm", "user_auth"]],
        ["in", "application_name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Set_entry_result", "http://www.sugarcrm.com/sugarcrm", "set_entry_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "is_loopback"),
      "http://crm.automatedlabs.com/soap.php/is_loopback",
      "is_loopback",
      [ ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "seamless_login"),
      "http://crm.automatedlabs.com/soap.php/seamless_login",
      "seamless_login",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_entry_list"),
      "http://crm.automatedlabs.com/soap.php/get_entry_list",
      "get_entry_list",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "query", ["::SOAP::SOAPString"]],
        ["in", "order_by", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "select_fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["in", "max_results", ["::SOAP::SOAPInt"]],
        ["in", "deleted", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["Get_entry_list_result", "http://www.sugarcrm.com/sugarcrm", "get_entry_list_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_entry"),
      "http://crm.automatedlabs.com/soap.php/get_entry",
      "get_entry",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "id", ["::SOAP::SOAPString"]],
        ["in", "select_fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["retval", "return", ["Get_entry_result", "http://www.sugarcrm.com/sugarcrm", "get_entry_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_entries"),
      "http://crm.automatedlabs.com/soap.php/get_entries",
      "get_entries",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "ids", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["in", "select_fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["retval", "return", ["Get_entry_result", "http://www.sugarcrm.com/sugarcrm", "get_entry_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_entry"),
      "http://crm.automatedlabs.com/soap.php/set_entry",
      "set_entry",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "name_value_list", ["Name_value_list", "http://www.sugarcrm.com/sugarcrm", "name_value_list"]],
        ["retval", "return", ["Set_entry_result", "http://www.sugarcrm.com/sugarcrm", "set_entry_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_entries"),
      "http://crm.automatedlabs.com/soap.php/set_entries",
      "set_entries",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "name_value_lists", ["Name_value_lists", "http://www.sugarcrm.com/sugarcrm", "name_value_lists"]],
        ["retval", "return", ["Set_entries_result", "http://www.sugarcrm.com/sugarcrm", "set_entries_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_note_attachment"),
      "http://crm.automatedlabs.com/soap.php/set_note_attachment",
      "set_note_attachment",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "note", ["Note_attachment", "http://www.sugarcrm.com/sugarcrm", "note_attachment"]],
        ["retval", "return", ["Set_entry_result", "http://www.sugarcrm.com/sugarcrm", "set_entry_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_note_attachment"),
      "http://crm.automatedlabs.com/soap.php/get_note_attachment",
      "get_note_attachment",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "id", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Return_note_attachment", "http://www.sugarcrm.com/sugarcrm", "return_note_attachment"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "relate_note_to_module"),
      "http://crm.automatedlabs.com/soap.php/relate_note_to_module",
      "relate_note_to_module",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "note_id", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "module_id", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Error_value", "http://www.sugarcrm.com/sugarcrm", "error_value"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_related_notes"),
      "http://crm.automatedlabs.com/soap.php/get_related_notes",
      "get_related_notes",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "module_id", ["::SOAP::SOAPString"]],
        ["in", "select_fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["retval", "return", ["Get_entry_result", "http://www.sugarcrm.com/sugarcrm", "get_entry_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "logout"),
      "http://crm.automatedlabs.com/soap.php/logout",
      "logout",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Error_value", "http://www.sugarcrm.com/sugarcrm", "error_value"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_module_fields"),
      "http://crm.automatedlabs.com/soap.php/get_module_fields",
      "get_module_fields",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Module_fields", "http://www.sugarcrm.com/sugarcrm", "module_fields"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_available_modules"),
      "http://crm.automatedlabs.com/soap.php/get_available_modules",
      "get_available_modules",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Module_list", "http://www.sugarcrm.com/sugarcrm", "module_list"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "update_portal_user"),
      "http://crm.automatedlabs.com/soap.php/update_portal_user",
      "update_portal_user",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "portal_name", ["::SOAP::SOAPString"]],
        ["in", "name_value_list", ["Name_value_list", "http://www.sugarcrm.com/sugarcrm", "name_value_list"]],
        ["retval", "return", ["Error_value", "http://www.sugarcrm.com/sugarcrm", "error_value"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "test"),
      "http://crm.automatedlabs.com/soap.php/test",
      "test",
      [ ["in", "string", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_user_id"),
      "http://crm.automatedlabs.com/soap.php/get_user_id",
      "get_user_id",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_user_team_id"),
      "http://crm.automatedlabs.com/soap.php/get_user_team_id",
      "get_user_team_id",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_server_time"),
      "http://crm.automatedlabs.com/soap.php/get_server_time",
      "get_server_time",
      [ ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_gmt_time"),
      "http://crm.automatedlabs.com/soap.php/get_gmt_time",
      "get_gmt_time",
      [ ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_sugar_flavor"),
      "http://crm.automatedlabs.com/soap.php/get_sugar_flavor",
      "get_sugar_flavor",
      [ ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_server_version"),
      "http://crm.automatedlabs.com/soap.php/get_server_version",
      "get_server_version",
      [ ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_relationships"),
      "http://crm.automatedlabs.com/soap.php/get_relationships",
      "get_relationships",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "module_id", ["::SOAP::SOAPString"]],
        ["in", "related_module", ["::SOAP::SOAPString"]],
        ["in", "related_module_query", ["::SOAP::SOAPString"]],
        ["in", "deleted", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["Get_relationships_result", "http://www.sugarcrm.com/sugarcrm", "get_relationships_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_relationship"),
      "http://crm.automatedlabs.com/soap.php/set_relationship",
      "set_relationship",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "set_relationship_value", ["Set_relationship_value", "http://www.sugarcrm.com/sugarcrm", "set_relationship_value"]],
        ["retval", "return", ["Error_value", "http://www.sugarcrm.com/sugarcrm", "error_value"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_relationships"),
      "http://crm.automatedlabs.com/soap.php/set_relationships",
      "set_relationships",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "set_relationship_list", ["Set_relationship_list", "http://www.sugarcrm.com/sugarcrm", "set_relationship_list"]],
        ["retval", "return", ["Set_relationship_list_result", "http://www.sugarcrm.com/sugarcrm", "set_relationship_list_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_document_revision"),
      "http://crm.automatedlabs.com/soap.php/set_document_revision",
      "set_document_revision",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "note", ["Document_revision", "http://www.sugarcrm.com/sugarcrm", "document_revision"]],
        ["retval", "return", ["Set_entry_result", "http://www.sugarcrm.com/sugarcrm", "set_entry_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "search_by_module"),
      "http://crm.automatedlabs.com/soap.php/search_by_module",
      "search_by_module",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "search_string", ["::SOAP::SOAPString"]],
        ["in", "modules", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "max_results", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["Get_entry_list_result", "http://www.sugarcrm.com/sugarcrm", "get_entry_list_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_mailmerge_document"),
      "http://crm.automatedlabs.com/soap.php/get_mailmerge_document",
      "get_mailmerge_document",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "file_name", ["::SOAP::SOAPString"]],
        ["in", "fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["retval", "return", ["Get_sync_result_encoded", "http://www.sugarcrm.com/sugarcrm", "get_sync_result_encoded"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_mailmerge_document2"),
      "http://crm.automatedlabs.com/soap.php/get_mailmerge_document2",
      "get_mailmerge_document2",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "file_name", ["::SOAP::SOAPString"]],
        ["in", "fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["retval", "return", ["Get_mailmerge_document_result", "http://www.sugarcrm.com/sugarcrm", "get_mailmerge_document_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_document_revision"),
      "http://crm.automatedlabs.com/soap.php/get_document_revision",
      "get_document_revision",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "i", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Return_document_revision", "http://www.sugarcrm.com/sugarcrm", "return_document_revision"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_campaign_merge"),
      "http://crm.automatedlabs.com/soap.php/set_campaign_merge",
      "set_campaign_merge",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "targets", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["in", "campaign_id", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Error_value", "http://www.sugarcrm.com/sugarcrm", "error_value"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_entries_count"),
      "http://crm.automatedlabs.com/soap.php/get_entries_count",
      "get_entries_count",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "query", ["::SOAP::SOAPString"]],
        ["in", "deleted", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["Get_entries_count_result", "http://www.sugarcrm.com/sugarcrm", "get_entries_count_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "set_entries_details"),
      "http://crm.automatedlabs.com/soap.php/set_entries_details",
      "set_entries_details",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "name_value_lists", ["Name_value_lists", "http://www.sugarcrm.com/sugarcrm", "name_value_lists"]],
        ["in", "select_fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["retval", "return", ["Set_entries_detail_result", "http://www.sugarcrm.com/sugarcrm", "set_entries_detail_result"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "sync_get_modified_relationships"),
      "http://crm.automatedlabs.com/soap.php/sync_get_modified_relationships",
      "sync_get_modified_relationships",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "related_module", ["::SOAP::SOAPString"]],
        ["in", "from_date", ["::SOAP::SOAPString"]],
        ["in", "to_date", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "max_results", ["::SOAP::SOAPInt"]],
        ["in", "deleted", ["::SOAP::SOAPInt"]],
        ["in", "module_id", ["::SOAP::SOAPString"]],
        ["in", "select_fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["in", "ids", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["in", "relationship_name", ["::SOAP::SOAPString"]],
        ["in", "deletion_date", ["::SOAP::SOAPString"]],
        ["in", "php_serialize", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["Get_entry_list_result_encoded", "http://www.sugarcrm.com/sugarcrm", "get_entry_list_result_encoded"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_modified_entries"),
      "http://crm.automatedlabs.com/soap.php/get_modified_entries",
      "get_modified_entries",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "ids", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["in", "select_fields", ["Select_fields", "http://www.sugarcrm.com/sugarcrm", "select_fields"]],
        ["retval", "return", ["Get_sync_result_encoded", "http://www.sugarcrm.com/sugarcrm", "get_sync_result_encoded"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_attendee_list"),
      "http://crm.automatedlabs.com/soap.php/get_attendee_list",
      "get_attendee_list",
      [ ["in", "session", ["::SOAP::SOAPString"]],
        ["in", "module_name", ["::SOAP::SOAPString"]],
        ["in", "id", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Get_sync_result_encoded", "http://www.sugarcrm.com/sugarcrm", "get_sync_result_encoded"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "create_session"),
      "http://crm.automatedlabs.com/soap.php/create_session",
      "create_session",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "end_session"),
      "http://crm.automatedlabs.com/soap.php/end_session",
      "end_session",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "contact_by_email"),
      "http://crm.automatedlabs.com/soap.php/contact_by_email",
      "contact_by_email",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "email_address", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Contact_detail_array", "http://www.sugarcrm.com/sugarcrm", "contact_detail_array"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "get_contact_relationships"),
      "http://crm.automatedlabs.com/soap.php/get_contact_relationships",
      "get_contact_relationships",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "id", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Contact_detail_array", "http://www.sugarcrm.com/sugarcrm", "contact_detail_array"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "user_list"),
      "http://crm.automatedlabs.com/soap.php/user_list",
      "user_list",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["User_detail_array", "http://www.sugarcrm.com/sugarcrm", "user_detail_array"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "search"),
      "http://crm.automatedlabs.com/soap.php/search",
      "search",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["Contact_detail_array", "http://www.sugarcrm.com/sugarcrm", "contact_detail_array"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "track_email"),
      "http://crm.automatedlabs.com/soap.php/track_email",
      "track_email",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "parent_id", ["::SOAP::SOAPString"]],
        ["in", "contact_ids", ["::SOAP::SOAPString"]],
        ["in", "date_sent", ["::SOAP::SOAPDate"]],
        ["in", "email_subject", ["::SOAP::SOAPString"]],
        ["in", "email_body", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "create_contact"),
      "http://crm.automatedlabs.com/soap.php/create_contact",
      "create_contact",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "first_name", ["::SOAP::SOAPString"]],
        ["in", "last_name", ["::SOAP::SOAPString"]],
        ["in", "email_address", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "create_lead"),
      "http://crm.automatedlabs.com/soap.php/create_lead",
      "create_lead",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "first_name", ["::SOAP::SOAPString"]],
        ["in", "last_name", ["::SOAP::SOAPString"]],
        ["in", "email_address", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "create_account"),
      "http://crm.automatedlabs.com/soap.php/create_account",
      "create_account",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "name", ["::SOAP::SOAPString"]],
        ["in", "phone", ["::SOAP::SOAPString"]],
        ["in", "website", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "create_opportunity"),
      "http://crm.automatedlabs.com/soap.php/create_opportunity",
      "create_opportunity",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "name", ["::SOAP::SOAPString"]],
        ["in", "amount", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsSugarcrm, "create_case"),
      "http://crm.automatedlabs.com/soap.php/create_case",
      "create_case",
      [ ["in", "user_name", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

